### ISSUE TITLE
PRolly use property version for spring-boot-dependencies?

### ISSUE THREAD

**Issue by mykelalvis** [byronic/spaced#1]
[This code](https://github.com/byronic/spaced/blob/main/pom.xml#L42-L48) could be changed to use
```
        <version>${spring.boot.version}</version>
```

**Comment by byronic** [comment]
I didn't even notice that had been updated in the parent. :facepalm: - https://github.com/infrastructurebuilder/ibparent/blob/ibparent-80/pom.xml#L231
